[default.probe]
protocol = "Swd"
speed = 20000

[default.flashing]
enabled = true

[default.reset]
enabled = true
halt_afterwards = false

[default.general]
chip = "RP2040"
# RP2040 does not support connect_under_reset
connect_under_reset = false

# No log prints if `cargo embed` is used
[default.rtt]
enabled = false

# Use `cargo embed log` to enable log prints
[log.rtt]
enabled = true

[default.gdb]
enabled = false
gdb_connection_string = "127.0.0.1:2345"
